# Generated by Django 4.1.7 on 2023-04-04 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lunbo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageurl', models.CharField(max_length=128)),
                ('jumpurl', models.CharField(max_length=128)),
                ('is_start', models.IntegerField(default=0)),
                ('creat_time', models.DateTimeField(auto_now_add=True)),
                ('updata_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phototitle', models.CharField(max_length=128)),
                ('photoall', models.CharField(max_length=4096)),
                ('creat_time', models.DateTimeField(auto_now_add=True)),
                ('updata_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usermini',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=64)),
                ('token', models.CharField(max_length=64)),
                ('avator_img', models.CharField(max_length=64)),
                ('stu_name', models.CharField(max_length=64)),
                ('stu_school', models.CharField(max_length=64)),
                ('telphone', models.CharField(max_length=64)),
                ('is_admin', models.IntegerField(default=0)),
                ('creat_time', models.DateTimeField(auto_now_add=True)),
                ('updata_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Videolive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageurl', models.CharField(max_length=128)),
                ('title', models.CharField(max_length=128)),
                ('start_time', models.CharField(max_length=128)),
                ('videolive_name', models.CharField(max_length=128)),
                ('creat_time', models.DateTimeField(auto_now_add=True)),
                ('updata_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameField(
            model_name='article',
            old_name='readnum',
            new_name='createbyname',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='is_login',
            new_name='is_admin',
        ),
        migrations.RemoveField(
            model_name='article',
            name='language',
        ),
        migrations.RemoveField(
            model_name='article',
            name='type',
        ),
        migrations.AddField(
            model_name='users',
            name='updata_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
