# Generated by Django 4.1.7 on 2023-04-08 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_photo_remove_photos_photoall'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermini',
            name='avator_img',
            field=models.CharField(max_length=256),
        ),
    ]
