# Generated by Django 4.1.7 on 2023-04-08 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_alter_usermini_avator_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lunbo',
            name='jumpurl',
            field=models.CharField(max_length=256),
        ),
    ]
