# Generated by Django 4.1.7 on 2023-04-09 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_alter_lunbo_jumpurl'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sceneryid', models.CharField(max_length=128)),
                ('commentbyopenid', models.CharField(max_length=128)),
                ('commentbynickname', models.CharField(max_length=128)),
                ('commentcontent', models.CharField(max_length=128)),
                ('creat_time', models.DateTimeField(auto_now_add=True)),
                ('updata_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageurl', models.CharField(max_length=256)),
                ('longitude', models.CharField(max_length=256)),
                ('latitude', models.CharField(max_length=256)),
                ('bynickname', models.CharField(max_length=256)),
                ('byopenid', models.CharField(max_length=256)),
                ('notes', models.CharField(max_length=256)),
                ('is_pass', models.IntegerField(default=0)),
                ('passbyname', models.CharField(max_length=128)),
                ('creat_time', models.DateTimeField(auto_now_add=True)),
                ('updata_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inviteopenid', models.CharField(max_length=128)),
                ('invitenickname', models.CharField(max_length=128)),
                ('invitewxid', models.CharField(max_length=128)),
                ('age', models.IntegerField()),
                ('sex', models.CharField(max_length=128)),
                ('timeline', models.CharField(max_length=128)),
                ('speed', models.CharField(max_length=128)),
                ('roadline', models.CharField(max_length=128)),
                ('otherinfo', models.CharField(max_length=128)),
                ('creat_time', models.DateTimeField(auto_now_add=True)),
                ('updata_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lvdao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.CharField(max_length=256)),
                ('latitude', models.CharField(max_length=256)),
                ('creat_time', models.DateTimeField(auto_now_add=True)),
                ('updata_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ridinginfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(max_length=128)),
                ('nickname', models.CharField(max_length=128)),
                ('speed', models.CharField(max_length=128)),
                ('longitude', models.CharField(max_length=256)),
                ('latitude', models.CharField(max_length=256)),
                ('height', models.CharField(max_length=128)),
                ('accuracy', models.CharField(max_length=128)),
                ('creat_time', models.DateTimeField(auto_now_add=True)),
                ('updata_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RidingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ridingopenid', models.CharField(max_length=128)),
                ('ridingnickname', models.CharField(max_length=128)),
                ('date', models.CharField(max_length=128)),
                ('starttime', models.IntegerField()),
                ('longtime', models.CharField(max_length=128)),
                ('distance', models.CharField(max_length=128)),
                ('Gate', models.CharField(max_length=128)),
                ('creat_time', models.DateTimeField(auto_now_add=True)),
                ('updata_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Scenery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('content', models.CharField(max_length=512)),
                ('byopenid', models.CharField(max_length=128)),
                ('bynickname', models.CharField(max_length=128)),
                ('creat_time', models.DateTimeField(auto_now_add=True)),
                ('updata_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SceneryPhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sceneryid', models.CharField(max_length=128)),
                ('photourl', models.CharField(max_length=256)),
                ('creat_time', models.DateTimeField(auto_now_add=True)),
                ('updata_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Userminis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=64)),
                ('openid', models.CharField(max_length=128)),
                ('avator_img', models.CharField(max_length=256)),
                ('creat_time', models.DateTimeField(auto_now_add=True)),
                ('updata_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='Lunbo',
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
        migrations.DeleteModel(
            name='Photos',
        ),
        migrations.DeleteModel(
            name='Usermini',
        ),
        migrations.DeleteModel(
            name='Videolive',
        ),
    ]
