# Generated by Django 4.1.7 on 2023-04-09 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0006_comment_gate_invite_lvdao_ridinginfo_ridingplan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenery',
            name='is_pass',
            field=models.IntegerField(default=0),
        ),
    ]
