# Generated by Django 4.1.7 on 2023-04-10 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0008_lunbo'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='imageurl',
            field=models.CharField(default=111, max_length=128),
            preserve_default=False,
        ),
    ]
