# Generated by Django 4.1.7 on 2023-04-10 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0009_invite_imageurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='age',
            field=models.CharField(max_length=128),
        ),
    ]
