# Generated by Django 4.1.7 on 2023-04-10 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0010_alter_invite_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenery',
            name='cover',
            field=models.CharField(default=11, max_length=256),
            preserve_default=False,
        ),
    ]
