# Generated by Django 4.1.7 on 2023-04-11 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0011_scenery_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='avator_url',
            field=models.CharField(default=11, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scenery',
            name='avator_url',
            field=models.CharField(default=111111, max_length=128),
            preserve_default=False,
        ),
    ]
