# Generated by Django 4.1.7 on 2023-04-11 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0012_comment_avator_url_scenery_avator_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ridingplan',
            name='starttime',
            field=models.CharField(max_length=128),
        ),
    ]
