# Generated by Django 4.1.7 on 2023-05-16 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0013_alter_ridingplan_starttime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=256)),
                ('password', models.CharField(max_length=128)),
                ('is_superadmin', models.IntegerField(default=0)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=256)),
                ('image_url', models.CharField(max_length=256)),
                ('image_type', models.CharField(max_length=256)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Records',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=128)),
                ('images_id', models.CharField(max_length=512)),
                ('level', models.CharField(max_length=256)),
                ('is_finshed', models.IntegerField(default=0)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Gate',
        ),
        migrations.DeleteModel(
            name='Invite',
        ),
        migrations.DeleteModel(
            name='Lvdao',
        ),
        migrations.DeleteModel(
            name='Ridinginfo',
        ),
        migrations.DeleteModel(
            name='RidingPlan',
        ),
        migrations.DeleteModel(
            name='Scenery',
        ),
        migrations.DeleteModel(
            name='SceneryPhotos',
        ),
        migrations.DeleteModel(
            name='Userminis',
        ),
        migrations.RenameField(
            model_name='lunbo',
            old_name='creat_time',
            new_name='create_time',
        ),
        migrations.RenameField(
            model_name='lunbo',
            old_name='updata_time',
            new_name='update_time',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='creat_time',
            new_name='create_time',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='updata_time',
            new_name='update_time',
        ),
        migrations.RemoveField(
            model_name='lunbo',
            name='imageurl',
        ),
        migrations.RemoveField(
            model_name='lunbo',
            name='jumpurl',
        ),
        migrations.RemoveField(
            model_name='users',
            name='is_admin',
        ),
        migrations.AddField(
            model_name='lunbo',
            name='lunbo_url',
            field=models.CharField(default=11, max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='avatar_url',
            field=models.CharField(default=1, max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='nickname',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(max_length=128),
        ),
    ]
