# Generated by Django 4.1.7 on 2023-05-17 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0014_admins_images_records_delete_comment_delete_gate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='password',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='username',
            new_name='gender',
        ),
        migrations.AddField(
            model_name='users',
            name='openid',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
    ]
